FROM golang:1.18.0-alpine AS build
RUN apk add git
RUN mkdir /builddir
ADD . /builddir
WORKDIR /builddir
RUN go build ./cmd/popplesvc

FROM alpine:latest
COPY --from=build /builddir/popplesvc /usr/local/bin/popplesvc

ENTRYPOINT ["/usr/local/bin/popplesvc"]