// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ResponseWriter is an autogenerated mock type for the ResponseWriter type
type ResponseWriter struct {
	mock.Mock
}

// React provides a mock function with given fields: emoji
func (_m *ResponseWriter) React(emoji string) error {
	ret := _m.Called(emoji)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(emoji)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMessageToChannel provides a mock function with given fields: msg
func (_m *ResponseWriter) SendMessageToChannel(msg string) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendReply provides a mock function with given fields: msg
func (_m *ResponseWriter) SendReply(msg string) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
