// Code generated by sqlc. DO NOT EDIT.

package sqlite

import (
	"time"
)

type Config struct {
	ID         int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ServerID   string
	NoAnnounce bool
}

type Entity struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ServerID  string
	Karma     int64
}
