name: Docker

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
      matrix:
        target: [linux/amd64, linux/arm64]
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Set up Docker BuildX
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: false
        platforms: ${{ matrix.target }}
